postgres:
  image: kiasaki/alpine-postgres:9.5
  volumes:
    - pg_data:/var/lib/postgresql/data
    - ./sql/:/docker-entrypoint-initdb.d/
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: content_user